language: node_js

node_js:
  - node

notifications:
  email: false

sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

install:
  - yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - yarn build

script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e --headless
  - yarn test:e2e:browsers

after_script:
  - yarn deploy
