language: node_js

node_js:
  - lts/*

notifications:
  email: false

dist: xenial
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
     - fluxbox 
     - ffmpeg
     - libgconf-2-4

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - stty cols 80

install:
  - yarn install --frozen-lockfile

before_script:
  - "export DISPLAY=:99.0"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - yarn build

script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e --headless
  - yarn test:testcafe

after_script:
  - yarn deploy
