language: node_js

node_js:
  - lts/*

notifications:
  email: false

dist: xenial
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
     - fluxbox 
     - ffmpeg
     - libgconf-2-4

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - stty cols 80

install:
  - yarn install --frozen-lockfile
  - yarn cypress verify || yarn cypress install

before_script:
  - "export DISPLAY=:99.0"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

stages:
  - lint
  - test
  - e2e
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: lint
      name: Lint source files
      script:
        - yarn lint
    - stage: test
      name: Run unit tests
      script:
        - yarn test:unit
    - stage: e2e
      name: Run Cypress tests
      script:
        - yarn test:e2e --headless
    - stage: e2e
      name: Run TestCafe tests
      script:
        - yarn test:testcafe
    - stage: deploy
      script:
        - yarn build
        - yarn deploy