language: node_js

node_js:
  - 10

notifications:
  email: false

dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - stty cols 80
  - npm i -g http-server

install:
  - yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - yarn build
  - http-server -s dist &

script:
  - yarn lint
  - yarn test:unit
  - yarn test:e2e --headless --record --key 00d0788b-7e9c-43f8-9c7c-5009a21dad3a
  - yarn test:e2e:browsers

after_script:
  - yarn deploy
