name: CI test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: haya14busa/action-cond@v1
      id: reporter
      with:
        cond: ${{ github.event_name == 'pull_request' }}
        if_true: "github-pr-review"
        if_false: "github-check"
    - uses: actions/checkout@v2
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: --ext '.js' --ext '.vue' .
        reporter: ${{ steps.reporter.outputs.value }}

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: npm test
      run: |
        npm run test:unit

  cypress:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      timeout-minutes: 10
      env:
        CYPRESS_baseUrl: http://localhost:8080
      with:
        start: npm run serve
        wait-on: http://localhost:8080

  testcafe:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Run TestCafe
      run: |
        yarn add -O @ffmpeg-installer/ffmpeg
        yarn test:testcafe
